// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var UIUtils$ReactTemplate = require("./UIUtils.bs.js");

function addToStorage(name) {
  return (function (param) {
      param.setItem(name, "yo");
      return /* () */0;
    });
}

var component = ReasonReact.reducerComponent("CardGameAdd");

function make(dispatch, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "row"
                        }, React.createElement("h2", undefined, UIUtils$ReactTemplate.str("Add a game")), React.createElement("div", {
                              className: "row"
                            }, React.createElement("button", {
                                  className: "btn waves-effect waves-light pink",
                                  onClick: (function (_event) {
                                      return Curry._1(dispatch, /* AddGame */Block.__(2, ["testagame"]));
                                    })
                                }, UIUtils$ReactTemplate.str("Add yo"))));
            }),
          /* initialState */(function (param) {
              return /* record */[/* gameName */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* gameName */"yo"]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.addToStorage = addToStorage;
exports.component = component;
exports.make = make;
/* component Not a pure module */
