// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Types$ReactTemplate = require("./Types.bs.js");
var UIUtils$ReactTemplate = require("./UIUtils.bs.js");

var component = ReasonReact.statelessComponent("CardSetView");

function make(cardset, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var match = Belt_Option.isNone(cardset[/* cards */3]);
              return React.createElement("div", {
                          className: "row"
                        }, React.createElement("h2", undefined, UIUtils$ReactTemplate.str(cardset[/* name */1])), React.createElement("h3", undefined, UIUtils$ReactTemplate.str(cardset[/* description */2])), React.createElement("p", undefined, match ? UIUtils$ReactTemplate.str("No card yet in this card set") : UIUtils$ReactTemplate.str(String(Curry._1(Types$ReactTemplate.IntMap[/* cardinal */15], Belt_Option.getExn(cardset[/* cards */3]))) + " card(s) in this set")), $$Array.of_list(List.map((function (param) {
                                    var card = param[1];
                                    var match = card[/* keyword */3];
                                    return React.createElement("div", {
                                                key: String(param[0]),
                                                className: "card"
                                              }, React.createElement("div", {
                                                    className: "card-content"
                                                  }, React.createElement("h4", undefined, UIUtils$ReactTemplate.str(card[/* name */1]))), React.createElement("div", {
                                                    className: "card-content grey lighten-4"
                                                  }, UIUtils$ReactTemplate.str(card[/* text */2])), React.createElement("div", {
                                                    className: "card-content indigo lighten-4"
                                                  }, match ? React.createElement("p", undefined, UIUtils$ReactTemplate.str("CREATURE")) : React.createElement("p", undefined, UIUtils$ReactTemplate.str("GEAR"))));
                                  }), Curry._1(Types$ReactTemplate.IntMap[/* bindings */16], Belt_Option.getExn(cardset[/* cards */3])))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
