// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Types$ReactTemplate = require("./Types.bs.js");
var UIUtils$ReactTemplate = require("./UIUtils.bs.js");

function handleClick(href, $$event) {
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    return ReasonReact.Router[/* push */0](href);
  }
}

var component = ReasonReact.statelessComponent("GamesList");

function make(games, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "row"
                        }, React.createElement("h2", undefined, UIUtils$ReactTemplate.str("List of games")), React.createElement("div", {
                              className: "collection"
                            }, $$Array.of_list(List.map((function (x) {
                                        var cardGame = x[1];
                                        var match = Belt_Option.isNone(cardGame[/* cardSets */3]);
                                        return React.createElement("a", {
                                                    key: String(x[0]),
                                                    className: "collection-item avatar",
                                                    href: "#",
                                                    onClick: Curry._1(self[/* handle */0], (function ($$event, param) {
                                                            return handleClick("/cardgame/" + String(cardGame[/* id */0]), $$event);
                                                          }))
                                                  }, React.createElement("i", {
                                                        className: "material-icons circle"
                                                      }, UIUtils$ReactTemplate.str("videogame_asset")), React.createElement("span", {
                                                        className: "title blue-text text-darken-2"
                                                      }, UIUtils$ReactTemplate.str($$String.uppercase(cardGame[/* name */1]))), React.createElement("p", undefined, UIUtils$ReactTemplate.str(match ? "No cardset yet" : String(Curry._1(Types$ReactTemplate.IntMap[/* cardinal */15], Belt_Option.getExn(cardGame[/* cardSets */3]))) + " cardset(s)"), React.createElement("br", undefined)));
                                      }), Curry._1(Types$ReactTemplate.IntMap[/* bindings */16], games)))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.handleClick = handleClick;
exports.component = component;
exports.make = make;
/* component Not a pure module */
