// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var UIUtils$ReactTemplate = require("./UIUtils.bs.js");

function handleClick(href, $$event) {
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    return ReasonReact.Router[/* push */0](href);
  }
}

var component = ReasonReact.statelessComponent("GamesList");

function make(games, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "row"
                        }, React.createElement("h2", undefined, UIUtils$ReactTemplate.str("List of games")), UIUtils$ReactTemplate.componentsListToArray(games, (function (game) {
                                return React.createElement("div", {
                                            key: game,
                                            className: "row"
                                          }, React.createElement("a", {
                                                className: "waves-effect waves-light btn green lighten-1",
                                                onClick: Curry._1(self[/* handle */0], (function ($$event, param) {
                                                        return handleClick("/cardgame/" + game, $$event);
                                                      }))
                                              }, UIUtils$ReactTemplate.str(game)));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.handleClick = handleClick;
exports.component = component;
exports.make = make;
/* component Not a pure module */
