// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var UIUtils$ReactTemplate = require("./UIUtils.bs.js");

function handleClick(href, $$event) {
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    return ReasonReact.Router[/* push */0](href);
  }
}

var component = ReasonReact.statelessComponent("GamesList");

function make(games, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "row"
                        }, React.createElement("h2", undefined, UIUtils$ReactTemplate.str("List of games")), React.createElement("div", {
                              className: "collection"
                            }, UIUtils$ReactTemplate.componentsListToArray(games, (function (game) {
                                    return React.createElement("a", {
                                                key: game[/* name */1],
                                                className: "collection-item avatar",
                                                href: "#",
                                                onClick: Curry._1(self[/* handle */0], (function ($$event, param) {
                                                        return handleClick("/cardgame/" + String(game[/* id */0]), $$event);
                                                      }))
                                              }, React.createElement("i", {
                                                    className: "material-icons circle"
                                                  }, UIUtils$ReactTemplate.str("videogame_asset")), React.createElement("span", {
                                                    className: "title blue-text text-darken-2"
                                                  }, UIUtils$ReactTemplate.str($$String.uppercase(game[/* name */1]))), React.createElement("p", undefined, UIUtils$ReactTemplate.str("2 cardsets"), React.createElement("br", undefined), UIUtils$ReactTemplate.str("10 cards")));
                                  }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.handleClick = handleClick;
exports.component = component;
exports.make = make;
/* component Not a pure module */
