// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Types$ReactTemplate = require("./Types.bs.js");

var woodplate = /* record */[
  /* id */0,
  /* name */"Wood plate",
  /* text */"A simple but robust plate made of wood",
  /* keyword : GEAR */0
];

var mechaBunny = /* record */[
  /* id */1,
  /* name */"Mecha Bunny",
  /* text */"Hopping mech style",
  /* keyword : CREATURE */1
];

var startingCards = Curry._3(Types$ReactTemplate.IntMap[/* add */3], 1, mechaBunny, Types$ReactTemplate.IntMap[/* empty */0]);

var startingCards$1 = Curry._3(Types$ReactTemplate.IntMap[/* add */3], 0, woodplate, startingCards);

var startingCardSet = Curry._3(Types$ReactTemplate.IntMap[/* add */3], 0, /* record */[
      /* id */0,
      /* name */"Basic set of cards",
      /* description */"yolo",
      /* cards */Caml_option.some(startingCards$1)
    ], Types$ReactTemplate.IntMap[/* empty */0]);

function simpleInitialState(param) {
  return /* record */[
          /* view : HomeView */0,
          /* nextId */1,
          /* activeGameId */0,
          /* activeCardSetId */undefined,
          /* games */Curry._3(Types$ReactTemplate.IntMap[/* add */3], 0, /* record */[
                /* id */0,
                /* name */"Starting game",
                /* description */"Not to start empty is a good thing",
                /* cardSets */Caml_option.some(startingCardSet)
              ], Types$ReactTemplate.IntMap[/* empty */0])
        ];
}

exports.woodplate = woodplate;
exports.mechaBunny = mechaBunny;
exports.startingCards = startingCards$1;
exports.startingCardSet = startingCardSet;
exports.simpleInitialState = simpleInitialState;
/* startingCards Not a pure module */
