// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var UIUtils$ReactTemplate = require("./UIUtils.bs.js");
var StoryPointComponent$ReactTemplate = require("./StoryPointComponent.bs.js");

var addon = /* record */[
  /* id */999,
  /* text */"Im the addon",
  /* linkTo */1000
];

var storyComponent = ReasonReact.reducerComponent("StoryComponent");

function make(initialStory, _children) {
  return /* record */[
          /* debugName */storyComponent[/* debugName */0],
          /* reactClassInternal */storyComponent[/* reactClassInternal */1],
          /* handedOffState */storyComponent[/* handedOffState */2],
          /* willReceiveProps */storyComponent[/* willReceiveProps */3],
          /* didMount */storyComponent[/* didMount */4],
          /* didUpdate */storyComponent[/* didUpdate */5],
          /* willUnmount */storyComponent[/* willUnmount */6],
          /* willUpdate */storyComponent[/* willUpdate */7],
          /* shouldUpdate */storyComponent[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, React.createElement("p", undefined, self[/* state */1][/* story */1][/* name */0]), React.createElement("p", undefined, "Story points:", String(List.length(self[/* state */1][/* story */1][/* storyPoints */1]))), React.createElement("button", {
                              onClick: (function (_event) {
                                  return Curry._1(self[/* send */3], /* Add */0);
                                })
                            }, "Add a story point"), React.createElement("div", undefined, UIUtils$ReactTemplate.componentsListToArray(self[/* state */1][/* story */1][/* storyPoints */1], (function (storypoint) {
                                    return ReasonReact.element(String(storypoint[/* id */0]), undefined, StoryPointComponent$ReactTemplate.make(storypoint[/* id */0], storypoint[/* text */1], /* array */[]));
                                  }))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* count */0,
                      /* story */initialStory
                    ];
            }),
          /* retainedProps */storyComponent[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[
                          /* count */state[/* count */0],
                          /* story : record */[
                            /* name */state[/* story */1][/* name */0],
                            /* storyPoints */List.concat(/* :: */[
                                  state[/* story */1][/* storyPoints */1],
                                  /* :: */[
                                    /* :: */[
                                      addon,
                                      /* [] */0
                                    ],
                                    /* [] */0
                                  ]
                                ])
                          ]
                        ]]);
            }),
          /* jsElementWrapped */storyComponent[/* jsElementWrapped */13]
        ];
}

exports.addon = addon;
exports.storyComponent = storyComponent;
exports.make = make;
/* storyComponent Not a pure module */
