// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var storyPointComponent = ReasonReact.statelessComponent("StoryPointComponent");

function make(id, text, _children) {
  return /* record */[
          /* debugName */storyPointComponent[/* debugName */0],
          /* reactClassInternal */storyPointComponent[/* reactClassInternal */1],
          /* handedOffState */storyPointComponent[/* handedOffState */2],
          /* willReceiveProps */storyPointComponent[/* willReceiveProps */3],
          /* didMount */storyPointComponent[/* didMount */4],
          /* didUpdate */storyPointComponent[/* didUpdate */5],
          /* willUnmount */storyPointComponent[/* willUnmount */6],
          /* willUpdate */storyPointComponent[/* willUpdate */7],
          /* shouldUpdate */storyPointComponent[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col s12 m7"
                            }, React.createElement("div", {
                                  className: "card"
                                }, React.createElement("div", {
                                      className: "card-content"
                                    }, React.createElement("span", {
                                          className: "card-title"
                                        }, String(id)), text))));
            }),
          /* initialState */storyPointComponent[/* initialState */10],
          /* retainedProps */storyPointComponent[/* retainedProps */11],
          /* reducer */storyPointComponent[/* reducer */12],
          /* jsElementWrapped */storyPointComponent[/* jsElementWrapped */13]
        ];
}

exports.storyPointComponent = storyPointComponent;
exports.make = make;
/* storyPointComponent Not a pure module */
