// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var compare = Caml_obj.caml_compare;

var IntMap = $$Map.Make(/* module */[/* compare */compare]);

exports.IntMap = IntMap;
/* IntMap Not a pure module */
