// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function str(prim) {
  return prim;
}

function componentsListToArray(components, componentfn) {
  return $$Array.of_list(List.map(componentfn, components));
}

exports.str = str;
exports.componentsListToArray = componentsListToArray;
/* No side effect */
